# Site
name: "Buy Bitcoin in Seconds and Instant Bitcoin Exchange."
title: "Overblock"
description: ""
logo: 'assets/images/logos/logo.svg'
favicon: 'assets/images/logos/favicon.ico'
baseurl: ''
otc_url: 'https://overblock.io'
exchange_url: 'https://overblock.io'
segment_analytics: 'VwY5GjJUlhVHbYuWaR2iStUaziqDJ3O9'
disqus: ''
mailchimp-list: 'https://overblock.us20.list-manage.com/subscribe/post?u=323fbdc123af3c6269263c126&id=c5dbd760b4'
include: ["_pages"]
permalink: /:title

# Authors
authors:
  carlos:
    name: Carlos
    display_name: Carlos
    gravatar: 2b5034357be2b9fe6285ec359e265c0c
    email: carlos@overblock.io
    web: https://overblock.io
    twitter: https://twitter.com/caherrerapa
    description: 'from Overblock'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, 404.html]
